name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
    - name: Rename directories
      run: |
        mkdir 4.40
        mv Binary_4.40 4.40/Widgets.Bronto
        mv Source_4.40 4.40/Nop.Plugin.Widgets.Bronto
    - uses: dfar-io/nopcommerce-uploadeditems-action@v0.1
      with:
        plugin-name: 'Nop.Plugin.Widgets.Bronto'
    - name: Zip artifact files
      run: 7z a Bronto.zip .
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: Bronto.zip
